### ISSUE TITLE
Import-Module error

### ISSUE THREAD

**Issue by maxferrario-msf** [compelx/lawnchair#1]
Hi,
when launching via lawnchair a script that uses the AzureAD module I get this error, even if the script runs from powershell without issues because I am working on a 64bit machine.

>Import-Module : The current processor architecture is: X86.  The module 'C:\Program
Files\WindowsPowerShell\Modules\AzureAD\2.0.2.76\AzureAD.psd1' requires the following architecture: Amd64.
>At D:\users\REDACTED\documents\WindowsPowerShell\List-AdSyncronizedUsers.ps1:9 char:1
>  Import-Module AzureAD
>  ~~~~~~~~~~~~~~~~~~~~~
>  CategoryInfo          : ResourceUnavailable: (C:\Program File...76\AzureAD.psd1:String) [Import-Module], Invalid OperationException
>  FullyQualifiedErrorId : >Modules_InvalidProcessorArchitecture,Microsoft.PowerShell.Commands.ImportModuleCommand`
Any idea on how to solve the issue?

**Comment by compelx** [comment]
Its because the PowerShell process is being created from a 32bit process. Fow now, I have created a 64bit version of lawnchair which specifically targets x64. Try this executable instead. You can rename it if you wish.


[Lawnchair_64.zip](https://github.com/compelx/lawnchair/files/4698251/Lawnchair_64.zip)

**Comment by maxferrario-msf** [comment]
Thanks a lot Ryan, now the error is gone!
